//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplication.Models
{
    using Microsoft.AspNetCore.Identity;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Admins:IdentityUser<int>
    {
        [Key]
        public int idAdmin { get; set; }
        public string nameAdmin { get; set; }
        [EmailAddress]
        [DisplayName("Email")]
        [Required(ErrorMessage ="This field is required")]
        public string emailAdmin { get; set; }
        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This field is required")]
        public string passwordAdmin { get; set; }
        public string phoneAdmin { get; set; }
        [DataType(DataType.Date)]
        public DateTime Created { get; set; }

    }
}
