//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
   

    public partial class patients
    {
        [Key]
        public int idPatients { get; set; }
        public string namePatients { get; set; }
        public string phonePatients { get; set; }
        public Nullable<int> gender { get; set; }
        public string health_condition { get; set; }
        public Nullable<int> doctor_id { get; set; }
        public Nullable<int> nurse_id { get; set; }
        public DateTime Created { get; set; }
    
        public virtual doctors doctors { get; set; }
        public virtual nurses nurses { get; set; }
    }
}
